### ISSUE TITLE
DS Site - Компоненты - Datepicker

### ISSUE THREAD

**Issue by dariawish** [OpenVTB/react-ui-kit#117]
Позволяет вносить некорректные значения:

![image 21](https://user-images.githubusercontent.com/71381005/95073914-4d26de80-0716-11eb-8d81-f56acfdc55e3.png)

**Comment by PoltP** [comment]
У нас нет описания поведения в случае ввода некорректных значений (валидация и тп).
Сейчас такой ввод не выберет дату фактически - она будет null.
