### ISSUE TITLE
DS Site - Компоненты - Dropdown Button 

### ISSUE THREAD

**Issue by dariawish** [OpenVTB/react-ui-kit#121]
Dropdown button
Overflow Menu несколько портит композицию. Плюс описанная раннее ошибка с отступом в выпадающем меню
<img width="641" alt="Снимок экрана 2020-10-05 в 14 25 38" src="https://user-images.githubusercontent.com/71381005/95074129-ad1d8500-0716-11eb-8a7b-c3ca7f5ddd31.png">

**Comment by kateviditory** [comment]
Отступ я поправила в пул реквесте https://github.com/OpenVTB/react-ui-kit/pull/126

А неправильная композиция уже видимо поправлена в мастере, так как ее воспроизведение я не вижу. На https://openvtb.github.io/react-ui-kit/#/uikit/?component=Dropdown%20Button сейчас устаревшая версия компонента, после обновления, ошибка должна исчезнуть

**Comment by kateviditory** [comment]
Ошибка с композицией по-прежнему есть на демо сайте, буду разбираться, почему она осталась

**Comment by kateviditory** [comment]
Влила в мастер фикс ошибки с композицией
