### ISSUE TITLE
DS Site - Компоненты - Text Area 

### ISSUE THREAD

**Issue by dariawish** [OpenVTB/react-ui-kit#157]
Text Area

- Мы не ограничиваем по количеству строк, надо убрать эту настройку. Высота компонента задается дизайнером в зависимости от контекста.

- Ширина поля может быть любой, так же как и у любого компонента Input, надо убрать эту настройку

- Комопнент не должен менять свою высоту в зависимости от количества введенного текста, его высота фиксированна и задается на этапе разработки.

- Ограничение количества символов задается разработчиком, по дефолту поставить 999 знаков

- Настройку “Возможность редактирования” перименовать в “Options”. Там сделать две радиокнопки Disabled и Read Only. В режиме Read Only компонент нельзя привести в активное состояния, он не реагирует на нажатие.

Макет лежит [тут](https://www.figma.com/file/G8Hu58qnwj9qq3CFhQxjkQ/Design-System-Site?node-id=1914%3A0&viewport=769%2C250%2C0.10264977067708969) Пример работы компонента можно посмотреть в ДС Carbon.

Слишком широкая полоска, должна быть 2px:
<img width="453" alt="Снимок экрана 2020-10-07 в 12 44 42" src="https://user-images.githubusercontent.com/71381005/95315215-e2eb7680-089a-11eb-8422-e6d8e01fd114.png">

**Comment by technostyle** [comment]
Реализовал требование
"Комопнент не должен менять свою высоту в зависимости от количества введенного текста, его высота фиксированна и задается на этапе разработки.",
получилось не очень. Неужели так оставляем?

![Screenshot from 2020-10-12 16-45-19](https://user-images.githubusercontent.com/26245578/95753550-74e3ec80-0caa-11eb-81a8-7accc254ecb1.png)
