### ISSUE TITLE
DS Site - Компоненты - Switch

### ISSUE THREAD

**Issue by dariawish** [OpenVTB/react-ui-kit#158]
Switch

Компонент “прыгает” при переключении состояний во всех размерах

**Comment by kateviditory** [comment]
Компонент в демо помещен в блок, который его постоянно центрирует. При выключении-включении свитча, у него меняется надпись и как следствие ширина, поэтому постоянно происходит перецентрирование ("прыжки"). Сам компонент работает корректно и при использовании пользователями проблем с прыжками не будет. Обсудила это с дизайнером, решили что задачу можно закрыть
