### ISSUE TITLE
У Grid нельзя убрать margin по сторонам

### ISSUE THREAD

**Issue by Meyzz** [OpenVTB/react-ui-kit#188]
Мне кажется было бы удобно, чтобы у grid была пропса, позволяющая убрать маржины слева и справа
![image](https://user-images.githubusercontent.com/31901886/95722483-a940b400-0c7c-11eb-9e46-f2fa86bd733d.png)

**Comment by PoltP** [comment]
Grid настолько не проработан, что такая опция там совсем мелочь по сравнению с другими вещами.
Кроме того, это всё лучше у дизайнера уточнять, мы такие штуки наверное сами не можем вносить.

**Comment by Meyzz** [comment]
> Grid настолько не проработан, что такая опция там совсем мелочь по сравнению с другими недоделками (планировали, что кто-то начнёт юзать в реальных сценариях и мы поправим всё).
> Кроме того, это всё лучше у дизайнера уточнять, мы такие штуки наверное сами не можем вносить.

понял, спасибо

**Comment by PoltP** [comment]
@Meyzz  на самом деле возможно есть смысл писать такие suggestions - вопрос только как лучше, чтобы сильно не засорить список issues. 
Вообще, сейчас в grid не хватает как раз фидбека по использованию - прежде всего насколько удобно задание количества колонок для данного разрешения - сейчас это сделано немного иначе, чем везде (обычно пишут что-то вроде xs=6 s=8 и тп)
