### ISSUE TITLE
Компонент Multiselect возникают ошибки

### ISSUE THREAD

**Issue by deynega-andrey** [OpenVTB/react-ui-kit#228]
При использовании компонента Multiselect в консоле появляются ошибки.
![multiselect1](https://user-images.githubusercontent.com/44522605/97398607-16f80b80-191e-11eb-9245-5887c0c838e7.png)
![multiselect2](https://user-images.githubusercontent.com/44522605/97398612-18c1cf00-191e-11eb-8dae-7bf2a99b4cf6.png)

**Comment by Meyzz** [comment]
+, у меня тоже, возникают вроде как после открытия селектов, не только мульти

**Comment by technostyle** [comment]
Первый warning был пофикшен в https://github.com/OpenVTB/react-ui-kit/pull/252
