### ISSUE TITLE
Select - $menuIsOpen

### ISSUE THREAD

**Issue by dmitrykuznetsovdev** [OpenVTB/react-ui-kit#249]
Warning: React does not recognize the `$menuIsOpen` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `$menuisopen` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

`"@openvtb/react-ui-kit": "^0.2.2",`

```
 <Select
       list={list}
       label="Сегмент"
       size="small"
       onChange={(value) => console.log('Value from changed input', value)}
/>
```

**Comment by technostyle** [comment]
В актуальной версии мастера подобный warning удалось поймать только для компонента MultiSelect. PR с фиксом https://github.com/OpenVTB/react-ui-kit/pull/252. Так или иначе, изменения коснулись и  компонента Select.
