### ISSUE TITLE
Верстка компонента Switch

### ISSUE THREAD

**Issue by dmitrykuznetsovdev** [OpenVTB/react-ui-kit#264]
`"@openvtb/react-ui-kit": "^0.2.2",`

<img width="925" alt="Screenshot 2020-11-10 at 17 48 43" src="https://user-images.githubusercontent.com/897840/98689726-4165b200-237d-11eb-9ba3-107a5d300406.png">

**Comment by kateviditory** [comment]
Если проблема в том, что тень заезжает на текст, то у нас также на макетах сделано. Обговорю этот момент еще раз с дизайнером

**Comment by dmitrykuznetsovdev** [comment]
> Если проблема в том, что тень заезжает на текст, то у нас также на макетах сделано. Обговорю этот момент еще раз с дизайнером

Выглядит как баг ))))

**Comment by kateviditory** [comment]
Спросила у дизайнера, пересечение тени и текста - осознанное решение, не баг) Эльдар это с целой командой дизайнеров обсуждал
