### ISSUE TITLE
Добавить инпут-компоненту DatePicker задавать ширину как у остальных инпутов

### ISSUE THREAD

**Issue by AlexRarus** [OpenVTB/react-ui-kit#305]
у компонента DatePicker есть только 2 заданные ширины - 248px и 320px, хотелось бы передавать ширину в качестве props как у остальных инпутов

**Comment by PoltP** [comment]
@AlexRarus 
Поговорил с дизайнером. 
Эльдар сказал, что да, размер самого инпута нужно давать менять и сделать как здесь (слева):
![image](https://user-images.githubusercontent.com/41975596/99782448-343d8580-2b2a-11eb-93ad-b8376ab0cadf.png)

**Comment by PoltP** [comment]
Несмотря на то, что DatePicker есть инпут, я пока не стал давать все проперти базового инпута, так как его мы создаём внтури - возможно в будущем понадобится унаследовать базовый интерфейс.
