### ISSUE TITLE
Демо сайт отображается некорректно

### ISSUE THREAD

**Issue by DrUNE** [OpenVTB/react-ui-kit#67]
Необходимо реализовать Landing Page согласно макетам.
Также необходимо адаптировать сайт для корректного отображения на мобильных устройствах

**Comment by PoltP** [comment]
**Fonts Section**, комментарии дизайнера:
![image](https://user-images.githubusercontent.com/41975596/96238544-49f9e100-0fa7-11eb-8b52-b85c3fe720dd.png)
1 => в комбике H1, H2 и тп выбираются стили
2 => при клике цвет в блоке 3 меняется
  active - залитый овал
  hover - залитый круг
  enable - незалитый круг
3 => введённый текст должен быть сразу вышеуказанного стиля и цвета
4 => меняет 5, сдвигая в сторону до следующих стилей

**Comment by PoltP** [comment]
Themes Section, комментарии дизайнера (Илья):
![image](https://user-images.githubusercontent.com/41975596/97556327-5ee46480-19ea-11eb-8242-6a0b7cf41425.png)

> просто инпут с кнопками
