### ISSUE TITLE
DS Site - Основные - Ресайз окна 

### ISSUE THREAD

**Issue by dariawish** [OpenVTB/react-ui-kit#97]
При ресайзе окна:
• Максимальная ширина контентной области 1216px при размере окна браузера 1600px и выше (пример поведения ДС Carbon)
• Максимальный отступ от бокового меню до контентной области 288px (равно ширине бокового меню.

![image 8](https://user-images.githubusercontent.com/71381005/95069821-e7cfef00-070f-11eb-9deb-f43b6babcee7.png)

**Comment by PoltP** [comment]
https://www.figma.com/file/G8Hu58qnwj9qq3CFhQxjkQ/Design-System-Site?node-id=1792%3A14909

**Comment by PoltP** [comment]
**Комментарий Эльдара**

У Carbon оно не во всю ширину экрана (у меня монитор 4К).
А в какой то момент перестает увеличивать ширину:
![image](https://user-images.githubusercontent.com/41975596/95756714-d27a3800-0cae-11eb-8aad-19448c0c4109.png)

**Comment by PoltP** [comment]
Также нужно пофиксить текстовую область - она должна быть 768px и не длиннее контентной области (что ниже), то есть, чтобы не выступала за неё:
<img width="1418" alt="text" src="https://user-images.githubusercontent.com/41975596/95766112-7669e080-0cbb-11eb-8808-3831b4ec5fe8.png">
